# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

username: admin
password: NokiaSrl1!
skip-verify: true
port: 57400
timeout: 10s
encoding: json_ietf

targets:
  leaf1:
    subscriptions:
      - srl_if_oper_state
      - srl_net_instance
      - srl_if_stats
      - srl_if_traffic_rate
      - srl_cpu
      - srl_mem
      - srl_bgp_stats
      - srl_ipv4_routes
      - srl_ipv6_routes
      - srl_apps  
  leaf2:
    subscriptions:
      - srl_if_oper_state
      - srl_net_instance
      - srl_if_stats
      - srl_if_traffic_rate
      - srl_cpu
      - srl_mem
      - srl_bgp_stats
      - srl_ipv4_routes
      - srl_ipv6_routes
      - srl_apps  
  leaf3:
    subscriptions:
      - srl_if_oper_state
      - srl_net_instance
      - srl_if_stats
      - srl_if_traffic_rate
      - srl_cpu
      - srl_mem
      - srl_bgp_stats
      - srl_ipv4_routes
      - srl_ipv6_routes
      - srl_apps  
  spine1:
    subscriptions:
      - srl_if_oper_state
      - srl_net_instance
      - srl_if_stats
      - srl_if_traffic_rate
      - srl_cpu
      - srl_mem
      - srl_bgp_stats
      - srl_ipv4_routes
      - srl_ipv6_routes
      - srl_apps  
  spine2:
    subscriptions:
      - srl_if_oper_state
      - srl_net_instance
      - srl_if_stats
      - srl_if_traffic_rate
      - srl_cpu
      - srl_mem
      - srl_bgp_stats
      - srl_ipv4_routes
      - srl_ipv6_routes
      - srl_apps  
  dcgw1:
    insecure: true
    password: NokiaSros1!
    subscriptions:
      - sros_if_oper_state
      - sros_vpls_instance_oper_state
      - sros_vpls_instance_oper_service_id
      - sros_vpls_instance_vxlan
      - sros_vpls_instance_bgp
      - sros_if_stats
      - sros_if_traffic_rate
      - sros_cpu
      - sros_mem
      - sros_bgp_stats
      - sros_bgp_up_peers
      - sros_bgp_neighbor_stats
      - sros_ipv4_stats
      - sros_ipv4_stats_direct
      - sros_ipv4_stats_bgp
      - sros_ipv6_stats
      - sros_ipv6_bgp_direct
      - sros_ipv4_routes
      - sros_ipv6_routes
      - sros_evpn_routes
      - sros_evpn_vxlan_vni
      - sros_vxlan_vteps
      - sros_vxlan_learned_macs
      - sros_bgp_neighbor_session_state
      - sros_bgp_routes_stats
      - sros_bgp_routes_active
      - sros_bgp_used_routes
      - sros_bgp_evpn_routes_active
      - sros_bgp_evpn_routes_suppressed
  dcgw2:
    insecure: true
    password: NokiaSros1!
    subscriptions:
      - sros_if_oper_state
      - sros_vpls_instance_oper_state
      - sros_vpls_instance_oper_service_id
      - sros_vpls_instance_vxlan
      - sros_vpls_instance_bgp
      - sros_if_stats
      - sros_if_traffic_rate
      - sros_cpu
      - sros_mem
      - sros_bgp_stats
      - sros_bgp_up_peers
      - sros_bgp_neighbor_stats
      - sros_ipv4_stats
      - sros_ipv4_stats_direct
      - sros_ipv4_stats_bgp
      - sros_ipv6_stats
      - sros_ipv6_bgp_direct
      - sros_ipv4_routes
      - sros_ipv6_routes
      - sros_evpn_routes
      - sros_evpn_vxlan_vni
      - sros_vxlan_vteps
      - sros_vxlan_learned_macs
      - sros_bgp_neighbor_session_state
      - sros_bgp_routes_stats
      - sros_bgp_routes_active
      - sros_bgp_used_routes
      - sros_bgp_evpn_routes_active
      - sros_bgp_evpn_routes_suppressed


subscriptions:
  ### SRL ###
  srl_if_oper_state:
    paths:
      - /interface[name=ethernet-1/*]/oper-state
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  srl_net_instance:
    paths:
      - /network-instance[name=*]/oper-state
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  srl_if_stats:
    paths:
      - /interface[name=ethernet-1/*]/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 5s
  
  srl_if_traffic_rate:
    paths:
      - /interface[name=ethernet-1/*]/traffic-rate
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  srl_cpu:
    paths:
      - /platform/control[slot=*]/cpu[index=all]/total
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  srl_mem:
    paths:
      - /platform/control[slot=*]/memory
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  srl_bgp_stats:
    paths:
      - /network-instance[name=*]/protocols/bgp/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  srl_ipv4_routes:
    paths:
      - /network-instance[name=*]/route-table/ipv4-unicast/statistics/
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  srl_ipv6_routes:
    paths:
      - /network-instance[name=*]/route-table/ipv6-unicast/statistics/
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  srl_apps:
    paths:
      - /system/app-management/application[name=*]
    mode: stream
    stream-mode: sample
    sample-interval: 5s
  

  ### SROS ###
  sros_if_oper_state:
    paths:
      - /state/port[port-id=*]/oper-state
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_vpls_instance_oper_state:
    paths:
      - /state/service/vpls[service-name=*]/oper-state
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_vpls_instance_oper_service_id:
    paths:
      - /state/service/vpls[service-name=*]/oper-service-id
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_vpls_instance_vxlan:
    paths:
      - /state/service/vpls[service-name=*]/vxlan
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_vpls_instance_bgp:
    paths:
      - /state/service/vpls[service-name=*]/bgp
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_if_stats:
    paths:
      - /state/port[port-id=*]/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_if_traffic_rate:
    paths:
      - /state/port[port-id=*]/ethernet/oper-speed
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_cpu:
    paths:
      - /state/system/cpu[sample-period=300]/system/cpu-usage
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_mem:
    paths:
      - /state/system/memory-pools
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_bgp_stats:
    paths:
      - /state/router[router-name=*]/bgp/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_bgp_up_peers:
    paths:
      - state/router[router-name=*]/bgp/convergence/family[family-type=ipv4]
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_bgp_neighbor_stats:
    paths:
      - /state/router[router-name=*]/bgp/neighbor[ip-address=*]/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_bgp_neighbor_session_state:
    paths:
      - /state/router[router-name=*]/bgp/neighbor[ip-address=*]/statistics/session-state
    mode: stream
    stream-mode: sample
    sample-interval: 5s


  sros_ipv4_stats:
    paths:
      - /state/router[router-name=*]/route-table/unicast/ipv4/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_ipv4_stats_direct:
    paths:
      - /state/router[router-name=*]/route-table/unicast/ipv4/statistics/direct
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_ipv4_stats_bgp:
    paths:
      - /state/router[router-name=*]/route-table/unicast/ipv4/statistics/bgp
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_ipv6_stats:
    paths:
      - /state/router[router-name=*]/route-table/unicast/ipv6/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_ipv6_bgp_direct:
    paths:
      - /state/router[router-name=*]/route-table/unicast/ipv6/statistics/direct
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_ipv4_routes:
    paths:
      - /state/router[router-name=*]/route-table/unicast/ipv4/route[ipv4-prefix=*]
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_ipv6_routes:
    paths:
      - /state/router[router-name=*]/route-table/unicast/ipv6/route[ipv6-prefix=*]
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_evpn_routes:
    paths:
      - /state/router[router-name=*]/bgp/statistics/routes-per-family/evpn
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_evpn_vxlan_vni:
    paths:
      - /state/service/vpls[service-name=*]/vxlan/instance[vxlan-instance=*]/destinations/non-ethernet-segment-destination[ip-address=*][vni=*]
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_vxlan_vteps:
    paths:
      - /state/service/vxlan/tep[ip-address=*]
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_vxlan_learned_macs:
    paths:
      - /state/service/vpls[service-name=*]/fdb/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 5s   
 
  sros_bgp_routes_stats:
    paths:
      - /state/router[router-name=*]/route-table/unicast/ipv4/statistics/bgp
    mode: stream
    stream-mode: sample
    sample-interval: 5s  

  sros_bgp_routes_active:
    paths:
      - /state/router[router-name=*]/bgp/neighbor[ip-address=*]/statistics/family-prefix/ipv4/active
    mode: stream
    stream-mode: sample
    sample-interval: 5s 

  sros_bgp_used_routes:
    paths:
      - /state/router[router-name=*]/bgp/rib/ipv6-unicast/local-rib/routes[prefix=*][neighbor=*][owner=*][router-instance-origin=*][path-id=*]/used-route
    mode: stream
    stream-mode: sample
    sample-interval: 5s 

  sros_bgp_evpn_routes_active:
    paths:
      - /state/router[router-name=*]/bgp/neighbor[ip-address=*]/statistics/family-prefix/evpn/active
    mode: stream
    stream-mode: sample
    sample-interval: 5s 

  sros_bgp_evpn_routes_suppressed:
    paths:
      - /state/router[router-name=*]/bgp/neighbor[ip-address=*]/statistics/family-prefix/evpn/suppressed
    mode: stream
    stream-mode: sample
    sample-interval: 5s 


outputs:
  prom:
    type: prometheus
    listen: :9273
    path: /metrics
    metric-prefix: gnmic
    append-subscription-name: true
    export-timestamps: true
    debug: false
    event-processors:
      - trim-prefixes
      - oper-state-to-int
      - rename-srl-interface
      - rename-port-sros
  #    - rename-port-value-sros
  # stdout:
  #   type: file
  #   file-type: stdout
  #   event-processors:
  #     - proc-convert-strings-to-int
  #     - trim-prefixes

processors:
  trim-prefixes:
    event-strings:
      value-names:
        - ".*"
      transforms:
        - path-base:
            apply-on: "name"
  oper-state-to-int:
    event-strings:
      value-names:
        - ".*"
      transforms:
        - replace:
            apply-on: "value"
            old: "up"
            new: "1"
        - replace:
            apply-on: "value"
            old: "down"
            new: "0"
  rename-srl-interface:
    event-strings:
      tag-names:
        - "^interface_name"
      transforms:
        - replace:
            apply-on: "value"
            old: "ethernet-(\\d+)/(\\d+)"
            new: "e$1-$2"
  rename-port-sros:
    event-strings:
      tag-names:
        - "^port_port-id"
      transforms:
        - replace:
            apply-on: "name"
            old: "port_port-id"
            new: "interface_name"
  rename-port-value-sros:
    event-strings:
      tag-names:
        - "^interface_name"
      transforms:
        - replace:
            apply-on: "value"
            old: ".*/c(\\d+)(/\\d+)?"
            new: "eth$1"
